name: 'cifar10_cnn_01'


model:
  name: vel.models.vision.cifar10_cnn_01
  img_rows: 32
  img_cols: 32
  img_channels: 3
  num_classes: 10

source:
  name: vel.sources.vision.cifar10
#  batch_size: 128
  batch_size: 32
  num_workers: 4
  normalize: True

  augmentations:
  - name: vel.augmentations.random_crop
    mode: x
    tags: ["train"]
    width: 32
    height: 32
    padding: 4
    padding_mode: 'reflect'

  - name: vel.augmentations.random_horizontal_flip
    mode: x
    tags: ["train"]

commands:
  train:
    name: vel.commands.train_command
    epochs: 12
    log_frequency: 20
    optimizer:
      name: vel.optimizers.adadelta
