name: 'cifar10_resnetv1_32'


model:
  name: vel.models.vision.cifar_resnext
  img_channels: 3
  num_classes: 10

  mode: bottleneck # Basic or bottleneck
  blocks: [3, 3, 3] # ResNext29
  inplanes: 256
  image_features: 64
  divisor: 4
  cardinality: 1

source:
  name: vel.sources.vision.cifar10
  batch_size: 128
#  batch_size: 32
  num_workers: 4
  normalize: True

  augmentations:
  - name: vel.augmentations.random_horizontal_flip
    mode: x
    tags: ["train"]
  - name: vel.augmentations.random_crop
    mode: x
    tags: ["train"]
    width: 32
    height: 32
    padding: 4
    padding_mode: 'reflect'


commands:
  train:
    name: vel.commands.train_command
    epochs: 300
    log_frequency: 100


    optimizer:
      name: vel.optimizers.sgd
      lr: 0.1
      weight_decay: 0.0001
      momentum: 0.9

#    optimizer:
#      name: vel.optimizers.adam
#      lr: 0.001
#      weight_decay: 0.001

#    scheduler:
#      name: vel.scheduler.multi_step
#      milestones: [20, 50, 100, 150]
#      gamma: 0.33

    scheduler:
      name: vel.scheduler.ladder
      ladder:
      - [150, 1.0]
      - [75, 0.1]
      - [75, 0.01]

#    scheduler:
#      name: vel.scheduler.reduce_lr_on_plateau
#      metric_name: val:accuracy
#      factor: 0.33
#      patience: 15
#      cooldown: 20
#      min_lr: 0.5e-6

  augvis:
    name: vel.commands.augvis_command
    samples: 5
