name: 'mnist_cnn_01'


model:
  name: vel.models.vision.mnist_cnn_01
  img_rows: 28
  img_cols: 28
  img_channels: 1
  num_classes: 10


source:
  name: vel.sources.vision.mnist
  batch_size: 128
  normalize: False
  num_workers: 4




commands:
  train:
    name: vel.commands.train_command
    epochs: 12
    log_frequency: 100

    optimizer:
      name: vel.optimizers.adadelta

    checkpoint:
      metric: 'val:loss'


  visdom:
    name: vel.commands.vis_store_command
